### ISSUE TITLE
v 2.X

### ISSUE THREAD

**Issue by mtncork** [aws-samples/amazon-qldb-dmv-sample-java#14]
The documentation at: https://docs.aws.amazon.com/qldb/latest/developerguide/runningsamples.html
says that there is a v2.0.0-rc.1 branch available. Trying to clone that I got an error. Also, I don't see it listed here.

Am I looking in the wrong spot ?
Thanks.

**Comment by yohanmartin** [comment]
Hello @mtncork ,
We have [`v2.0.0-rc.1`](https://github.com/aws-samples/amazon-qldb-dmv-sample-java/releases/tag/v2.0.0-rc.1) as a tag rather than a branch. You can check all the tags [here](https://github.com/aws-samples/amazon-qldb-dmv-sample-java/tags).  I ran the clone command mentioned in the documentation you pointed to and it did work fine for me. 

```
git clone -b v2.0.0-rc.1 git@github.com:aws-samples/amazon-qldb-dmv-sample-java.git
```
Could you confirm if you ran the same command? 

Also, the above command is the SSH version of the clone and it possible that there are issues with the SSH keys.
In that case, you can try the HTTPS version of the clone:

```
git clone -b v2.0.0-rc.1 https://github.com/aws-samples/amazon-qldb-dmv-sample-java.git
```

If you have not added SSH keys and want to do so, you can check this [how to add SSH keys to GitHub](https://help.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account).

Thank You.
