### ISSUE TITLE
Block transactionInfo hash is not contained in the QLDB block entries hash list when calling ValidateQldbHashChain 

### ISSUE THREAD

**Issue by 1Kunda** [aws-samples/amazon-qldb-dmv-sample-java#215]
When I try to execute a full hash chain validation on all the blocks in a ledger using the **ValidateQldbHashChain** class in the **amazon-qldb-dmv-sample-java 2.0** tutorial I get the error: `Block transactionInfo hash is not contained in the QLDB block entries hash list`.

I believe this is not supposed to be possible as the journal export to S3 is not tampered with in any way.

I've tried this using my local Eclipse environment and also using Cloud9 environment

Would love to hear from you regarding this issue.

**Comment by guyilin-amazon** [comment]
The `transactionInfo` hash is an optional field in the journal block. Some system blocks could be missing that and is expected behavior. 

The `ValidateQldbHashChain` class has been fixed to treat `transactionInfo` as an option field. Closing this issue, please feel free to reopen if the error happens again.
